---
title: "Experimentos en Redes"
author: 
- Natalia Perdomo & Valentina Cardona
- Email vcardonas@unal.edu.co
- GitHub https://github.com/vcardonas
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

# Introducción

En todas las ciencias existe un interés generalizado en evaluar el efecto de tratamientos o intervenciones de diversos tipos. Podría decirse que el ejemplo prototípico de este tipo de estudios es el **ensayo aleatorio** (en inglés, *randomized controlled trial*, RTC), también llamado como

$$Prueba\ A/B$$ Este diseño experimental convencional se caracteriza por dos aspectos principales:

1.  La noción de dos grupos a comparar (tratamiento y control, o A y B).
2.  La asignación aleatoria de individuos a dichos grupos.

Sin embargo, en estos experimentos suele asumirse que el tratamiento dado a un individuo no influye en los resultados de otros individuos (**no interferencia**).

Naturalmente, al realizar experimentos en redes no se puede descartar de manera realista la interferencia.

# Inferencia Causal Utilizando Resultados Potenciales

Supongamos que tenemos una población finita en la que queremos evaluar la eficacia de un tratamiento frente a un grupo control sin tratamiento, considerando una relación entre pares de individuos que se espera sea relevante para el experimento. Dicho escenario se verá representado por:

$$G=(V,E)$$ donde los vértices en $V$ corresponden a los $N_V$ individuos en la población, y las aristas en $E$ a sus relaciones.

Sea $z_i = 1$ para indicar que el individuo $i \in V$ recibió el tratamiento. Denotamos $\mathbf{z} = (z_1, \ldots, z_N)^T \in \{0, 1\}^N$ como el **vector de asignación de tratamientos**.

Un diseño experimental es una forma de elegir tal vector de tratamiento. Sea $p_{\mathbf{z}} = \mathbb{P}(\mathbf{Z} = \mathbf{z})$ la **probabilidad de que la asignación de tratamientos** $\mathbf{z}$ sea generada por el diseño.

Finalmente, sea $\theta_i(\mathbf{z})$ el **resultado para el individuo** $i$ bajo el tratamiento $\mathbf{z}$.

El **problema fundamental de la inferencia causal** es el hecho de que, aunque deseamos evaluar la diferencia en los resultados de los individuos bajo diferentes tratamientos, no podemos medir múltiples resultados simúltaneamente en un mismo individuo.

| Individuos | Mundo "ideal"      | Mundo "ideal"      | Mundo real         | Mundo real         |
|------------|--------------------|--------------------|--------------------|--------------------|
|            | $Z_i=0$            | $Z_i=1$            | $Z_i=0$            | $Z_i=1$            |
| 1          | $\mathscr{O}_1(0)$ | $\mathscr{O}_1(1)$ | $\mathscr{O}_1(0)$ | ?                  |
| 2          | $\mathscr{O}_2(0)$ | $\mathscr{O}_2(1)$ | ?                  | $\mathscr{O}_2(1)$ |

